### ISSUE TITLE
 Bucket在nuget中搜索不到, 示例项目编译不通过

### ISSUE THREAD

**Issue by colvinliu** [q315523275/FamilyBucket#1]
https://www.nuget.org/packages?q=Bucket
Bucket在nuget中搜索不到, 示例项目编译不通过。 git下来的示例等都编译不通过。 想弄个示例看看效果的。

**Comment by colvinliu** [comment]
项目包引用

针对对应项目进行打包，把打包文件放在一个统一的位置，Nuget设置一个本地路径即可



我吧项目编译后的dll都放到一个目录， sample 项目的Nuget添加了一个上面的目录， 还是不行呢。

**Comment by colvinliu** [comment]
![qq 20180911143230](https://user-images.githubusercontent.com/5326295/45342191-c0110a00-b5cf-11e8-9578-27ba742814cf.png)

![qq 20180911143256](https://user-images.githubusercontent.com/5326295/45342205-d0c18000-b5cf-11e8-8a4f-bc5357e39778.png)

**Comment by q315523275** [comment]
@colvinliu 近期更新一下，稍等

**Comment by q315523275** [comment]
@colvinliu 已更新nuget
