### ISSUE TITLE
如何在服务中使用消息订阅？

### ISSUE THREAD

**Issue by landonzeng** [q315523275/FamilyBucket#12]
看了demo中关于MQ的代码，有推送的demo，但是没看到从MQ中获取数据的demo，如果我要在controller中获取MQ中的数据要怎么写？

**Comment by q315523275** [comment]
首先mq是消息总线实现的一种方式
目前使用的是消息总线的方式中没有扩展controller可以获取mq消息的方法(可以增加属性和属性扫描实现自动订阅，controller添加属性然后就可以直接获取mq消息)
消息总线使用可以参考
消息处理器的注入
https://github.com/q315523275/FamilyBucket/blob/master/%E5%9F%BA%E7%A1%80%E6%9C%8D%E5%8A%A1%E9%A1%B9%E7%9B%AE/Pinzhi.BackgroundTasks/Pinzhi.BackgroundTasks/Startup.cs#L75
消息的订阅
https://github.com/q315523275/FamilyBucket/blob/master/%E5%9F%BA%E7%A1%80%E6%9C%8D%E5%8A%A1%E9%A1%B9%E7%9B%AE/Pinzhi.BackgroundTasks/Pinzhi.BackgroundTasks/Startup.cs#L107




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "landon"<notifications@github.com&gt;; 
发送时间: 2019年11月14日(星期四) 晚上6:17
收件人: "q315523275/FamilyBucket"<FamilyBucket@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [q315523275/FamilyBucket] 如何在服务中使用消息订阅？ (#12)




看了demo中关于MQ的代码，有推送的demo，但是没看到从MQ中获取数据的demo，如果我要在controller中获取MQ中的数据要怎么写？
 
&mdash;

**Comment by landonzeng** [comment]
消息推送的话，我知道是用  _eventBus 在构造函数中注入，然后在代码里直接用_eventBus.Publis()就可以推送了，如果我要取其中的消息，我要怎么做，就是这里很迷惑

**Comment by landonzeng** [comment]
哦哦，看到了，在Strartup中注入订阅， eventBus.Subscribe<UserActionEvent, UserActionEventHandler>();  然后在EventHandler中做对应的消息处理是吧

**Comment by q315523275** [comment]
是的，消息处理做好异常捕获，不进行异常捕获会阻塞队列




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"landon"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 晚上6:36
收件人:&nbsp;"q315523275/FamilyBucket"<FamilyBucket@noreply.github.com&gt;;
抄送:&nbsp;"田亮"<403305950@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [q315523275/FamilyBucket] 如何在服务中使用消息订阅？ (#12)




哦哦，看到了，在Strartup中注入订阅， eventBus.Subscribe<UserActionEvent, UserActionEventHandler&gt;();  然后在EventHandler中做对应的消息处理是吧

**Comment by landonzeng** [comment]
ok
